-- AlterTable
ALTER TABLE `Job` MODIFY `current_status` ENUM('DRAFT', 'BIDDING', 'PREPRINT', 'PRINTING', 'PREDELIVERY', 'REVIEW', 'ENROUTE', 'COMPLETE', 'CANCELED', 'READYFORPICKUP') NOT NULL DEFAULT 'DRAFT';
